/** A plain-language statement of how the app treats data and estimates. The
 *  whole app runs on-device with transparent, deterministic calculations; this
 *  panel makes that explicit so users know exactly what they're trusting. */
export function ResponsibleNote() {
  return (
    <section className="card responsible" aria-labelledby="responsibleHead">
      <h2 id="responsibleHead">🛡️ Responsible use, privacy &amp; the fine print</h2>
      <p className="hint">
        A tool about trust should be trustworthy. Here is how this one behaves.
      </p>
      <ul className="pledge">
        <li>
          <strong>Your data never leaves your device.</strong> Cases and history live only in
          this browser&rsquo;s local storage — no servers, accounts, cookies, tracking or
          analytics. Export a case file to keep it, or open a new case to wipe the slate.
        </li>
        <li>
          <strong>Estimates, not surveillance.</strong> Every figure is a transparent{" "}
          <em>typical annual estimate</em> from published emission factors, shown in full in
          the report&rsquo;s &ldquo;Show the working&rdquo; ledger. A real audit would measure
          your meters — treat these as directional.
        </li>
        <li>
          <strong>No black-box AI.</strong> Inspector Hoot is a scripted guide, not a model
          making decisions for you. Every number is a plain, inspectable calculation — nothing
          is generated by an AI, so nothing can be hallucinated or biased against you.
        </li>
        <li>
          <strong>Designed to be kind.</strong> The app nudges action, not anxiety — no dark
          patterns, no guilt-tripping, and full support for keyboard navigation and reduced
          motion.
        </li>
      </ul>
    </section>
  );
}
